name: BaseKit
description: Baseline modules and shared configuration for the BaseKit distribution.
type: recipe

install:
  # Core/contrib modules required by shared config and common features.
  - drupal:layout_builder
  - drupal:media
  - drupal:media_library
  - drupal:responsive_image
  - drupal:image
  - drupal:focal_point
  - drupal:views
  - drupal:editor
  - drupal:ckeditor5
  - drupal:rest
  - drupal:workflows
  # Admin UX
  - drupal:admin_toolbar
  - drupal:admin_toolbar_tools
  # Base content building blocks and storage.
  - drupal:block
  - drupal:block_content
  - drupal:field
  - drupal:text
  - drupal:node
  - drupal:taxonomy
  # Media, SVG, and image tooling
  - drupal:svg_image
  - drupal:inline_svg
  - drupal:crop
  # Layout builder enhancements and site UX
  - drupal:layout_builder_modal
  - drupal:layout_builder_styles
  - drupal:easy_breadcrumb
  - drupal:bg_image_formatter
  # Content formatting and developer tools
  - drupal:prism
  - drupal:profile
  - drupal:token
  # Navigation and content patterns
  - drupal:paragraphs
  - drupal:superfish
  - drupal:eva
  - drupal:swiper_formatter
  # Config management tooling
  - drupal:config_split

config:
  strict: false
  actions:
    # Example theme mapping for region blocks (add entries if you include them):
    # - config: block.block.gravelle1_site_branding
    #   op: set
    #   path: theme
    #   value: gravelle1
