name: BaseKit
description: Baseline modules and shared configuration for the BaseKit distribution.
type: recipe
core_version_requirement: ^11

install:
  # Core/contrib modules required by shared config and common features.
  - drupal:layout_builder
  - drupal:media
  - drupal:responsive_image
  - drupal:svg_image
  # Add validated plugin/schema providers often referenced by config.
  - drupal:image
  - drupal:views
  - drupal:editor
  - drupal:rest
  - drupal:workflows

config:
  import:
    - recipes/basekit/config
  actions:
    # Example theme mapping for region blocks (add entries if you include them):
    # - config: block.block.gravelle1_site_branding
    #   op: set
    #   path: theme
    #   value: gravelle1
