name: BaseKit
description: Baseline modules and shared configuration for the BaseKit distribution.
type: recipe

install:
  # Core/contrib modules required by shared config and common features.
  - drupal:layout_builder
  - drupal:media
  - drupal:media_library
  - drupal:responsive_image
  - drupal:image
  - drupal:views
  - drupal:editor
  - drupal:rest
  - drupal:workflows
  # Base content building blocks and storage.
  - drupal:block
  - drupal:block_content
  - drupal:field
  - drupal:text
  - drupal:node
  - drupal:taxonomy

config:
  import:
    - "*"
  actions:
    # Example theme mapping for region blocks (add entries if you include them):
    # - config: block.block.gravelle1_site_branding
    #   op: set
    #   path: theme
    #   value: gravelle1
