name: Block - Hero Headline
description: Custom block bundle hero_headline (type + fields + displays).
type: recipe
core_version_requirement: ^11

install:
  - drupal:block_content
  - drupal:field
  - drupal:text
  - drupal:image

config:
  import:
    - recipes/blocks/hero_headline/config
