name: Block - Hero Headline
description: Custom block bundle hero_headline (type + fields + displays).
type: recipe

install:
  - drupal:block_content
  - drupal:field
  - drupal:text
  - drupal:image

config:
  import:
    - "*"
