name: Site Aggregate
description: Aggregates BaseKit + features and sets the starter sub-theme.
type: recipe
 
install:
  - basekit
  - basekit_site
  - superfish

recipes:
  - basekit
  - article
  - blocks_hero_headline
  - blocks_hero_announcement
  - blocks_common
  - pages
  - paragraphs_base
  - profile_author
config:
  strict: false
  actions:
    system.theme:
      - op: set
        path: default
        value: basekit_site
      - op: set
        path: admin
        value: basekit_site
