name: Site Aggregate
description: Aggregates BaseKit + features and sets the starter sub-theme.
type: recipe
 
install:
  - basekit
  - basekit_site
  - superfish
  - simple_sitemap

recipes:
  - basekit
  - paragraphs_base
  - blocks_hero_headline
  - blocks_hero_announcement
  - blocks_common
  - pages
  - article
  - profile_author
config:
  strict: false
  actions:
    system.theme:
      simpleConfigUpdate:
        default: basekit_site
        admin: basekit_site
