name: Block - Hero Announcement
description: Custom block bundle hero_announcement (type + fields + displays).
type: recipe

install:
  - drupal:block_content
  - drupal:field
  - drupal:text
  - drupal:image

config:
  strict: false
