name: Article
description: Article content model (content type, fields, displays, roles, and related views).
type: recipe

install:
  - drupal:node
  - drupal:field
  - drupal:text
  - drupal:image
  - drupal:taxonomy

config:
  strict: false
